export const levels = {
    easy: [
      { theme: "Fruit", words: ["BANANA", "PAPAYA"] },
      { theme: "Colors", words: ["YELLOW", "VIOLET"] },
      { theme: "Metals", words: ["SILVER", "COPPER"] },
      { theme: "Oceans", words: ["ARCTIC", "INDIAN"] },
      { theme: "Animals", words: ["RABBIT", "MONKEY"] },
      { theme: "Seasons", words: ["WINTER", "AUTUMN"] }, 
      { theme: "Birds", boatName: "Bird", words: ["PIGEON", "FALCON"] },
      { theme: "Flowers", boatName: "Flower", words: ["TULIP", "DAISY"] },
      { theme: "Rivers", boatName: "River", words: ["THAMES", "AMAZON"] },
      { theme: "Shapes", boatName: "Shape", words: ["CIRCLE", "SQUARE"] },
      { theme: "Planets", boatName: "Planet", words: ["SATURN", "URANUS"] },
      { theme: "Gems", boatName: "Gem", words: ["EMERALD", "DIAMOND"] },
      { theme: "Trees", boatName: "Tree", words: ["BIRCH", "MAPLE"] },
      { theme: "Insects", boatName: "Insect", words: ["BEETLE", "HORNET"] },
      { theme: "Grains", boatName: "Grain", words: ["MILLET", "BARLEY"] },
      { theme: "Herbs", boatName: "Herb", words: ["BASIL", "THYME"] },
      { theme: "Deserts", boatName: "Desert", words: ["SAHARA", "MOJAVE"] },
      { theme: "Spices", boatName: "Spice", words: ["TURMERIC", "CARDAMOM"] }
    ],
    medium: [
      { theme: "Fabrics", boatName: "Fabric", words: ["CORDUROY", "CASHMERE"] },
      { theme: "Cheeses", boatName: "Cheese", words: ["RICOTTA", "CHEDDAR"] },
      { theme: "Islands", boatName: "Island", words: ["ICELAND", "JAMAICA"] },
      { theme: "Coffee", boatName: "Coffee", words: ["ARABICA", "ROBUSTA"] },
      { theme: "Fish", boatName: "Fish", words: ["HERRING", "SARDINE"] },
      { theme: "Storms", boatName: "Storm", words: ["CYCLONE", "TYPHOON"] },
      { theme: "Mushrooms", boatName: "Mushroom", words: ["BUTTON", "OYSTER"] },
      { theme: "Snakes", boatName: "Serpent", words: ["COTTONMOUTH", "RATTLESNAKE"] },
      { theme: "Painters", boatName: "Painter", words: ["MATISSE", "CEZANNE"] },
      { theme: "Dances", boatName: "Dance", words: ["FLAMENCO", "FANDANGO"] },
      { theme: "Planets", boatName: "Cosmic", words: ["CELESTIAL", "ASTRONAUT"] },
      { theme: "Authors", boatName: "Author", words: ["BRONTE", "AUSTEN"] },
      { theme: "Birdsofprey", boatName: "Bird of Prey", words: ["OSPREY", "CONDOR"] },
      { theme: "Herbs", boatName: "Herbal Hunter", words: ["OREGANO", "PARSLEY"] },
      { theme: "Mountains", boatName: "Mountain", words: ["EVEREST", "OLYMPUS"] },
      { theme: "Forests", boatName: "Forest", words: ["REDWOOD", "CYPRESS"] },
      { theme: "Desserts", boatName: "Dessert", words: ["BROWNIE", "CUPCAKE"] }
    ],
    hard: [
      { theme: "Greek Heroes", boatName: "Greek", words: ["HERCULES", "ACHILLES"] },
      { theme: "Galaxies", boatName: "Galaxy", words: ["ANDROMEDA", "WHIRLPOOL"] },
      { theme: "Wines", boatName: "Wine", words: ["RIESLING", "BORDEAUX"] },
      { theme: "Composers", boatName: "Composer", words: ["BERLIOZ", "VIVALDI"] },
      { theme: "Myths", boatName: "Mythic", words: ["PERSEUS", "THESEUS"] },
      { theme: "Butterflies", boatName: "Butterfly", words: ["MONARCH", "ADMIRAL"] },
      { theme: "Ancient Cities", boatName: "Ancient", words: ["BABYLON", "CARTHAGE"] },
      { theme: "Reptiles", boatName: "Reptile", words: ["TERRAPIN", "TORTOISE"] },
      { theme: "Cloud Types", boatName: "Cloud", words: ["CIRRUS", "CUMULUS"] },
      { theme: "Philosophers", boatName: "Philosopher", words: ["SOCRATES", "DIOGENES"] },
      { theme: "Alpine Peaks", boatName: "Alpine", words: ["MATTERHORN", "WEISSHORN"] },
      { theme: "Playwrights", boatName: "Drama", words: ["MARLOWE", "SOPHOCLES"] },
      { theme: "Tropical Fruit", boatName: "Tropic", words: ["AVOCADO", "TAMARIND"] },
      { theme: "Minerals", boatName: "Stone", words: ["OBSIDIAN", "DOLOMITE"] },
      { theme: "Astronomers", boatName: "Stellar", words: ["GALILEO", "KEPLERS"] },
      { theme: "Languages", boatName: "Tongue", words: ["MANDARIN", "JAPANESE"] },
      { theme: "Corals", boatName: "Coral", words: ["STAGHORN", "ELKHORNS"] },
      { theme: "Poets", boatName: "Verse", words: ["PETRARCH", "CHAUCERS"] },
      { theme: "Artists", boatName: "Art", words: ["REMBRANDT", "DELACROIX"] },
      { theme: "Volcanoes", boatName: "Fire", words: ["KRAKATOA", "VESUVIUS"] }
    ]
  };
  